{% set name = "colorcet" %}
{% set version = "3.1.0" %}
{% set sha256 = "2921b3cd81a2288aaf2d63dbc0ce3c26dcd882e8c389cc505d6886bf7aa9a4eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/{{ name }}/{{name}}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=30.3.0
    - setuptools_scm >=6
    - wheel
  run:
    - python

test:
  imports:
    - colorcet
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/holoviz/colorcet
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE.txt
  summary: Collection of perceptually uniform colormaps
  description: |
    HoloViz Colorcet provides perceptually accurate, 256-color colormaps,
    including both continuous and categorical types, designed for use with
    tools like Bokeh, Matplotlib, HoloViews, and Datashader.
  dev_url: https://github.com/holoviz/colorcet
  doc_url: https://colorcet.holoviz.org/user_guide/index.html

extra:
  recipe-maintainers:
    - jbednar
    - jsignell
