{% set name = "colorcet" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{name}}-{{ version }}.tar.gz
  sha256: 48d9a67e6e59dc5c0a965aa1b46fe5d59cdc95cc36a95949f29313f950ac59f7

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=30.3.0
    - setuptools_scm >=6
    - wheel
  run:
    - python

test:
  imports:
    - colorcet
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/holoviz/colorcet
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE.txt
  summary: Collection of perceptually uniform colormaps
  description: |
    HoloViz Colorcet provides perceptually accurate, 256-color colormaps,
    including both continuous and categorical types, designed for use with
    tools like Bokeh, Matplotlib, HoloViews, and Datashader.
  dev_url: https://github.com/holoviz/colorcet
  doc_url: https://colorcet.holoviz.org/user_guide/index.html

extra:
  recipe-maintainers:
    - jbednar
    - jsignell
