{% set name = "colorcet" %}
{% set version = "3.0.1" %}
{% set sha256 = "51455a20353d12fac91f953772d8409f2474e6a0db1af3fa4f7005f405a2480b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/{{ name }}/{{name}}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - colorcet = colorcet.__main__:main

requirements:
  host:
    - python
    - pip
    - pyct >=0.4.4
    - setuptools >=30.3.0
    - wheel
  run:
    - python
    - pyct >=0.4.4

test:
  imports:
    - colorcet
  requires:
    - pip
  commands:
    - pip check
    - colorcet --help

about:
  home: https://colorcet.holoviz.org/index.html
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE.txt
  summary: Collection of perceptually uniform colormaps
  description: |
    colorcet is a collection of perceptually uniform colormaps for use with
    Python plotting programs like bokeh, matplotlib, holoviews, and datashader.
  dev_url: https://github.com/holoviz/colorcet
  doc_url: https://colorcet.holoviz.org/user_guide/index.html

extra:
  recipe-maintainers:
    - jbednar
    - jsignell
