travis:
  secure:
    BINSTAR_TOKEN: TMsiPp18oLiPSyTzdAT68lBPHv2JlcHfkAf3JXwAKrWHA4za/5uPMb4AhUdomDWwuDypRRc5TR7C9QQkCtO3Av4ncn5PO79am+Ie4CYT7EqBzbe4kDlPv6Kjbys55NwsWbkpmjtlryBcOGewGGeOcMAKJScEB1WTpnHHZKgpiSR6kx7y1HiuhRK6jEdmtYpOqTsNl/tmcyNhNAwo9Rf3S5LYTd4wksLdCaVJpa6E8t+anFjr7/umR60GdnvtVgYtc5tNNiiCS6ng+BdwWOFPgBNNPeQvxsOUGb0p5PmvJEIxCWgcqLw85m0MMw8mpSooWAIzrA0dHw0A+cIypJdnDw93KTVRLPFIdK/SafCbYhl1X/xjfrOUNaXpJ6BrFk8z5ibO6LKW+Pc6ZWomeAbdZQT9YLa/lj8CrH9MNZGCAn8RyyXoN/9AiJL0bje37uCr+dq4HhsgdRYz/9J0A+B/qO3sWsmKg+/6Kt0qeWWMDl2VfHsM2goGjXelChL4w3ykY/i+3n95PWGPAFrD7p2QztJoIFeItXe+vvP2drZWKescgCjW5azxFoHwHbv7YoTVE2Jw2/4Jkv9Yv+L3F9p4T6BqICIK6yJoJ9EgDBEAWEgZcX2zIBjIBqc7eOwRVIbTIRq2OWz2WAW5YWErxk35Zm3oMPTgpHMId3jvBKLfyz0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
