travis:
  secure:
    BINSTAR_TOKEN: nPoqFoimeNtNO+EmORopiSMbqQtloS0YyyUdRIasZHOP1iNRBeer2aefzLZ+fYYpQOZUadU2eqBQr1M26UvSe/h8d6QDrXjghf/SM6DaJCNTETQ8ErfvFTe64OwCkThFpXdjJSpsCmO6TFu8xu5TZUFA1hgZhVNvi4GkchRdTVgAbTZ8E697QHMrjVkaqM7Fm+PJZZYYR2kuYHftwqxmBpWlwdZRq8emo3JVH95Hm7kq7uzDDZXQSbmd+ctGixCG2wZhUbtiR+ASqTxWvoat8DkuojcsgnenXG6gb35UzW7LGLA15ZXLwvDXLY7vWINOqR3yXAKC2M+JCEI5I2Wp+0SrWuumNjx04I3FcTcp/jFNW81z7BW5ux3TXVgNxgFmDKXJk5R4RJSSTl1BUiHt2RdDm9StgErX4wHFL1fQw09MoVRqmGSDZa5bn1X2u6u744kaH3eNjO8D9xrgVZ5g6f8rAf5gFf1lhdnghsakYs3/aEZgKwI2ZMo35gNplaZ39SCu1r6BOYzP3cbcKCpEkLLHFWvSkFOrCblNAOEp57H8bQDeynrK6VPmkZH10BI+c0zumsh3bdceiwpuk9CmfPDUYIsDh7j6GseXZ203eQfb2bI7gGaK3fC/WVV82z8JyMKi/qJC9DdsPGfMao8vWWAK0opAY+/Yu8x4Q/HmGLY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
